#services:
#  prometheus:
#    image: prom/prometheus:v2.35.0
#    network_mode: host
#    container_name: prometheus
#    restart: unless-stopped
#    volumes:
#      - ./data/prometheus/config:/etc/prometheus/
#    command:

#version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
networks:
  localprom:
    driver: bridge