
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro_cliente
    username: postgres
    password: Leonardo16@
  jpa:
    hibernate:
      #      dialect: org.hibernate.dialect.PostgreSQLDialect
      #      format_sql: true
      #      show_sql: true
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080


